# Generated by Django 3.1.2 on 2020-11-17 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceso',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 0, 26, 35, 467473)),
            preserve_default=False,
        ),
    ]
