# Generated by Django 3.1.2 on 2020-11-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20201117_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_entrada',
        ),
    ]
